[project]
name = "mri-art2-rbg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JuanPabloEspTEC", email = "a01646333@tec.mx" }
]
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.9",
    "networkx>=3.4.2",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pgmpy>=1.1.2",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
]

[project.scripts]
mri-art2-rbg = "mri_art2_rbg:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
